# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aye, Robot
tagline:          Machine Learnings
url:              http://fraglegs.github.io/poole/
paginate:         1
baseurl:          /
author:
  name:           Shayne Miel
  url:            https://twitter.com/
  email:          miel.shayne@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/FragLegs/poole
