# Permalinks
permalink:        pretty

# Setup
title:            Aye, Robot
tagline:          discere ex machina
url:
paginate:         1
baseurl:          /ayerobot/
author:
  name:           Shayne Miel
  url:            https://twitter.com/
  email:          miel.shayne@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/FragLegs/ayerobot

# Code highlighting
highlighter: pygments
